GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW5nbGUiLCJpYXQiOjE2NTU3MTcxMTAsImV4cCI6MTY1NTcxNzE0MH0.0kQtoG5ZhADi7gcqc5QF9rtJq32G9Vm-cEXqb50MYrk



###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW5nbGUiLCJpYXQiOjE2NTU3MTcwNjB9.IB9rSNyrlkxzLYzy3qgHSXdLEHTi83ZkKUeGQ_omjtY"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW5nbGUiLCJpYXQiOjE2NTU3MTcwNjB9.IB9rSNyrlkxzLYzy3qgHSXdLEHTi83ZkKUeGQ_omjtY"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Angle"
}